services:
  mysql:
    image: 'mysql:latest'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_spring_jpa
      MYSQL_PASSWORD: root
      TZ: America/Sao_Paulo
    ports:
      - '3306:3306'

volumes:
  mysql-data:
    driver: local
